### ISSUE TITLE
make install fails on macOS

### ISSUE THREAD

**Issue by cd-a** [PlankCipher/kabmat#14]
macOS 12.3.1
<img width="535" alt="Screenshot 2022-04-20 at 10 37 03" src="https://user-images.githubusercontent.com/75008413/164187323-5a186a86-4a8e-443d-9ac7-82c59647b851.png">

I do have coreutils installed via brew, so changing `install` to `ginstall` in the makefile makes it work.

Maybe there should be a check for OS version

**Comment by PlankCipher** [comment]
Or should we just revert back to regular `mkdir` and `cp` as before they were replaced with `install` in #4? I think having a system check and requiring `ginstall` is a bit of overkill. What do you think, @mdartmann?

**Comment by mdartmann** [comment]
Does macOS' `install` follow POSIX?

**Comment by mdartmann** [comment]
Actually, nevermind. `install` isn't POSIX at all, my bad. I'll rewrite the Makefile and use cp, mkdir and chmod instead.

**Comment by mdartmann** [comment]
Opened a PR that should fix this. I don't have a Mac to test on, but assuming MacOS follows POSIX, this should work. Sorry about that, I didn't know BSD install had this issue.
