### ISSUE TITLE
Using <C-h> (move column to the left) is not moving the focused column

### ISSUE THREAD

**Issue by hhhapz** [PlankCipher/kabmat#2]
The current key bind for trying to move the focused column is not causing it to move.

Moving the column to the right using <C-l> does work, however.

Steps to reproduce:

1. Create a new board
2. Add 2 columns
3. Move the leftmost column to the right (<C-l>)
4. Try to move it back to the left (<C-h>, FAIL)

**Comment by PlankCipher** [comment]
Odd! What terminal are you using?

**Comment by hhhapz** [comment]
Looks like this was only reproducible when I was sshing to a linux machine. Was unable to reproduce on a local native linux machine!

But the full setup, if you're curious is:
- Client Machine
  - MacOS
  - iTerm2
- Host Machine
  - Arch Linux

**Comment by PlankCipher** [comment]
I encountered this behavior once before, but couldn't reproduce it too. I think, most probably the key (`<C-h>`) isn't even reaching the program. Maybe it gets caught and handled by the terminal or something.

Anyway, I added `<C-p>` and `<C-n>` as alternatives to `<C-h>` and `<C-l>` respectively.
