### ISSUE TITLE
This works on Windows 10 Ubuntu WSL as well!

### ISSUE THREAD

**Issue by Gitleptune** [PlankCipher/kabmat#5]
I saw your note and I have it running fine on WSL on Windows.

![image](https://user-images.githubusercontent.com/76597257/161547172-9fe63492-544d-4ba2-94db-489c44b008e6.png)

If there's something else you would like me to try on WSL I can do it for you.

**Comment by PlankCipher** [comment]
Glad to know. Updating the README. Thanks!
