### ISSUE TITLE
[Bug report] The program don't open for me

### ISSUE THREAD

**Issue by Samuel-de-Oliveira** [PlankCipher/kabmat#7]
So i have installed Kabmat, but for any reason is giving me an error message like in the image:

![kabmat_error](https://user-images.githubusercontent.com/81493939/161742351-287e1dc7-845b-44d0-97e6-7313099833a9.png)

I tried use `--help` and `--version` parameters but it's give me the same error.

**Comment by PlankCipher** [comment]
Same as #3?

**Comment by Samuel-de-Oliveira** [comment]
Yeah, now it's working!
